apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: todoapp
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30050
  selector:
    app: todoapp
